# CI values for Xray

databaseUpgradeReady: yes
analysis:
  loggers:
    - xray_analysis.log

indexer:
  loggers:
    - xray_indexer.log
  persistence:
    enabled: true

persist:
  loggers:
    - xray_persist.log

server:
  loggers:
    - xray_server.log
  persistence:
    enabled: true

postgresql:
  postgresqlDatabase: xraydb
  postgresqlUser: xray
  postgresqlPassword: xray
  persistence:
    enabled: true

mongodb:
  mongodbRootPassword: password
  mongodbUsername: xray
  mongodbPassword: password
  mongodbDatabase: xray
  persistence:
    enabled: true

rabbitmq-ha:
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  persistentVolume:
    enabled: true
