dependencies:
- name: postgresql
  version: 9.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: rabbitmq
  version: 7.4.3
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
