# CI values for Distribution

databaseUpgradeReady: true
postgresql:
  postgresPassword: password
  persistence:
    enabled: false

redis:
  password: password
  persistence:
    enabled: false

distributor:
  persistence:
    enabled: false

distribution:
  persistence:
    enabled: false
