# CI values for Distribution

replicaCount: 2

databaseUpgradeReady: yes
postgresql:
  postgresPassword: password
  persistence:
    enabled: false

redis:
  password: password
  persistence:
    enabled: false

distributor:
  persistence:
    enabled: false

distribution:
  persistence:
    enabled: false

